name: 🪲 Bug
description: Report an issue to help improve the project.
title: "[Bug]: <title>"
labels: ['bug', 'triage']

body:

    -   type: markdown
        attributes:
            value: |
                Thanks for stopping by to let us know something could be better!

    -   type: markdown
        attributes:
            label: Is there an existing issue for this?
            value: |
                Please run down the following list and make sure you've tried the usual "quick fixes":

                -   https://github.com/AsifArmanRahman/firebase-rest-api/issues

    -   type: checkboxes
        attributes:
            options:
                -   label: I have searched the existing issues
                    required: true

    -   type: markdown
        attributes:
            value: |                
                If you are still having issues, please be sure to include as much information as possible:


    -   type: textarea
        attributes:
            label: Current Behavior
            description: A concise description of what you're experiencing.
        validations:
            required: false

    -   type: textarea
        attributes:
            label: Expected Behavior
            description: A concise description of what you expected to happen.
        validations:
            required: false

    -   type: textarea
        attributes:
            label: Steps To Reproduce
            description: Steps to reproduce the behavior.
            placeholder: |
                1. In this environment...
                2. With this config...
                3. Run '...'
                4. See error...
        validations:
            required: false

    -   type: textarea
        attributes:
            label: Environment
            description: |
                examples:
                -   **OS**: Ubuntu 20.04
                -   **Python**: 3.9.12
            value: |
                -   OS:
                -   Python:
            render: markdown
        validations:
            required: false

    -   type: textarea
        attributes:
            label: Anything else?
            description: |
                Links? References? Anything that will give us more context about the issue you are encountering!

                Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
        validations:
            required: false
