name: tests

# Controls when the workflow will run
on:
    # Triggers the workflow after 'Build' workflow completes running
    workflow_run:
        workflows: [ "build" ]
        branches: [ "main" ]
        types:
            - completed

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    # This workflow contains a single job called "tests"
    on_success:

        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Workflow will run only if the trigger workflow completed with success.
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v3

            -   name: Set up Python 3.9
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9
                    cache: pip

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
            -   name: Test with pytest and Generate Coverage report
                run: |
                    pytest --cov=simple_package

    on_faliure:

        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Workflow will run only if the trigger workflow completed with failure.
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        environment:
            name: Development

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:

            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v3

            -   name: Set up Python 3.9
                uses: actions/setup-python@v3
                with:
                    python-version: 3.9
                    cache: pip

            -   name: Force Fail
                run: |
                    exit 1